name: Deploy to ECR

on:
  push:
    branches:
    - main
  workflow_dispatch: {}

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        include:
        - app: download
          function: download-youtube-audio
        - app: feed
          function: process-youtube-feeds
        - app: update
          function: update-podcast-feed
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ matrix.app }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ${{ matrix.app }}
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: update-function
      env:
        IMAGE_URI: ${{ steps.build.outputs.image }}
      run: |
        aws lambda update-function-code --function-name arn:aws:lambda:us-east-1:${{ secrets.AWS_ACCOUNT_ID }}:function:${{ matrix.function}} --image-uri $IMAGE_URI

  upload-podcasts-config:
    name: Upload podcasts.json for config
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload file
      run: |
        aws s3 cp podcasts.json s3://podcasts.gtmanfred.com/podcasts.json
